// SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: power_grid.proto

// Service definition for power_grid_grpc_server: a gRPC front end for power-grid-model's power flow, state
// estimation, and short circuit calculations. Request/response payloads carry PGM's own input/output dataset
// JSON (the same schema used by power_grid_model_c_example/serialization.c) as string fields, rather than
// mirroring every component/attribute as protobuf messages — see grpc_server/README.md for the full field
// reference and for the internal/pgmtypes Go package that builds that JSON from typed structs.

package powergridpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PowerGridService_CalculatePowerFlow_FullMethodName                = "/power_grid_model.v1.PowerGridService/CalculatePowerFlow"
	PowerGridService_CalculateStateEstimation_FullMethodName          = "/power_grid_model.v1.PowerGridService/CalculateStateEstimation"
	PowerGridService_CalculateShortCircuit_FullMethodName             = "/power_grid_model.v1.PowerGridService/CalculateShortCircuit"
	PowerGridService_CreateModel_FullMethodName                       = "/power_grid_model.v1.PowerGridService/CreateModel"
	PowerGridService_DestroyModel_FullMethodName                      = "/power_grid_model.v1.PowerGridService/DestroyModel"
	PowerGridService_UpdateAndCalculatePowerFlow_FullMethodName       = "/power_grid_model.v1.PowerGridService/UpdateAndCalculatePowerFlow"
	PowerGridService_UpdateAndCalculateStateEstimation_FullMethodName = "/power_grid_model.v1.PowerGridService/UpdateAndCalculateStateEstimation"
	PowerGridService_UpdateAndCalculateShortCircuit_FullMethodName    = "/power_grid_model.v1.PowerGridService/UpdateAndCalculateShortCircuit"
)

// PowerGridServiceClient is the client API for PowerGridService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PowerGridService exposes power-grid-model calculations over gRPC. See src/power_grid_service.{hpp,cpp} for
// the server implementation and grpc_server/README.md for usage examples (grpcurl, Go clients).
type PowerGridServiceClient interface {
	// Runs a one-off power flow calculation against a complete input dataset (symmetric or asymmetric) and
	// returns the sym_output/asym_output dataset.
	CalculatePowerFlow(ctx context.Context, in *CalculatePowerFlowRequest, opts ...grpc.CallOption) (*CalculatePowerFlowResponse, error)
	// Runs a one-off state estimation calculation against a complete input dataset (including sensor
	// components) and returns the sym_output/asym_output dataset.
	CalculateStateEstimation(ctx context.Context, in *CalculateStateEstimationRequest, opts ...grpc.CallOption) (*CalculateStateEstimationResponse, error)
	// Runs a one-off IEC 60909 short circuit calculation against a complete input dataset (including at least
	// one fault) and returns the sc_output dataset (always per-phase a/b/c).
	CalculateShortCircuit(ctx context.Context, in *CalculateShortCircuitRequest, opts ...grpc.CallOption) (*CalculateShortCircuitResponse, error)
	// Builds a model from a complete input dataset and keeps it alive in server memory, returning a model_id
	// for use by the UpdateAndCalculate*/DestroyModel RPCs below. See the "Stateful model session API" note
	// above. The model has no expiry; call DestroyModel when done with it.
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	// Removes and frees the model for model_id. NOT_FOUND if it doesn't exist. Safe to call even while a call
	// against that model_id is in flight elsewhere.
	DestroyModel(ctx context.Context, in *DestroyModelRequest, opts ...grpc.CallOption) (*DestroyModelResponse, error)
	// Applies an (optionally empty) update dataset to an existing model, runs a power flow calculation, and
	// returns the result — without rebuilding topology from scratch. NOT_FOUND if model_id doesn't exist.
	UpdateAndCalculatePowerFlow(ctx context.Context, in *UpdateAndCalculatePowerFlowRequest, opts ...grpc.CallOption) (*CalculatePowerFlowResponse, error)
	// As UpdateAndCalculatePowerFlow, but runs a state estimation calculation. NOT_FOUND if model_id doesn't
	// exist.
	UpdateAndCalculateStateEstimation(ctx context.Context, in *UpdateAndCalculateStateEstimationRequest, opts ...grpc.CallOption) (*CalculateStateEstimationResponse, error)
	// As UpdateAndCalculatePowerFlow, but runs an IEC 60909 short circuit calculation. NOT_FOUND if model_id
	// doesn't exist.
	UpdateAndCalculateShortCircuit(ctx context.Context, in *UpdateAndCalculateShortCircuitRequest, opts ...grpc.CallOption) (*CalculateShortCircuitResponse, error)
}

type powerGridServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPowerGridServiceClient(cc grpc.ClientConnInterface) PowerGridServiceClient {
	return &powerGridServiceClient{cc}
}

func (c *powerGridServiceClient) CalculatePowerFlow(ctx context.Context, in *CalculatePowerFlowRequest, opts ...grpc.CallOption) (*CalculatePowerFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePowerFlowResponse)
	err := c.cc.Invoke(ctx, PowerGridService_CalculatePowerFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) CalculateStateEstimation(ctx context.Context, in *CalculateStateEstimationRequest, opts ...grpc.CallOption) (*CalculateStateEstimationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateStateEstimationResponse)
	err := c.cc.Invoke(ctx, PowerGridService_CalculateStateEstimation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) CalculateShortCircuit(ctx context.Context, in *CalculateShortCircuitRequest, opts ...grpc.CallOption) (*CalculateShortCircuitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateShortCircuitResponse)
	err := c.cc.Invoke(ctx, PowerGridService_CalculateShortCircuit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, PowerGridService_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) DestroyModel(ctx context.Context, in *DestroyModelRequest, opts ...grpc.CallOption) (*DestroyModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyModelResponse)
	err := c.cc.Invoke(ctx, PowerGridService_DestroyModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) UpdateAndCalculatePowerFlow(ctx context.Context, in *UpdateAndCalculatePowerFlowRequest, opts ...grpc.CallOption) (*CalculatePowerFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePowerFlowResponse)
	err := c.cc.Invoke(ctx, PowerGridService_UpdateAndCalculatePowerFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) UpdateAndCalculateStateEstimation(ctx context.Context, in *UpdateAndCalculateStateEstimationRequest, opts ...grpc.CallOption) (*CalculateStateEstimationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateStateEstimationResponse)
	err := c.cc.Invoke(ctx, PowerGridService_UpdateAndCalculateStateEstimation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridServiceClient) UpdateAndCalculateShortCircuit(ctx context.Context, in *UpdateAndCalculateShortCircuitRequest, opts ...grpc.CallOption) (*CalculateShortCircuitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateShortCircuitResponse)
	err := c.cc.Invoke(ctx, PowerGridService_UpdateAndCalculateShortCircuit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowerGridServiceServer is the server API for PowerGridService service.
// All implementations must embed UnimplementedPowerGridServiceServer
// for forward compatibility.
//
// PowerGridService exposes power-grid-model calculations over gRPC. See src/power_grid_service.{hpp,cpp} for
// the server implementation and grpc_server/README.md for usage examples (grpcurl, Go clients).
type PowerGridServiceServer interface {
	// Runs a one-off power flow calculation against a complete input dataset (symmetric or asymmetric) and
	// returns the sym_output/asym_output dataset.
	CalculatePowerFlow(context.Context, *CalculatePowerFlowRequest) (*CalculatePowerFlowResponse, error)
	// Runs a one-off state estimation calculation against a complete input dataset (including sensor
	// components) and returns the sym_output/asym_output dataset.
	CalculateStateEstimation(context.Context, *CalculateStateEstimationRequest) (*CalculateStateEstimationResponse, error)
	// Runs a one-off IEC 60909 short circuit calculation against a complete input dataset (including at least
	// one fault) and returns the sc_output dataset (always per-phase a/b/c).
	CalculateShortCircuit(context.Context, *CalculateShortCircuitRequest) (*CalculateShortCircuitResponse, error)
	// Builds a model from a complete input dataset and keeps it alive in server memory, returning a model_id
	// for use by the UpdateAndCalculate*/DestroyModel RPCs below. See the "Stateful model session API" note
	// above. The model has no expiry; call DestroyModel when done with it.
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	// Removes and frees the model for model_id. NOT_FOUND if it doesn't exist. Safe to call even while a call
	// against that model_id is in flight elsewhere.
	DestroyModel(context.Context, *DestroyModelRequest) (*DestroyModelResponse, error)
	// Applies an (optionally empty) update dataset to an existing model, runs a power flow calculation, and
	// returns the result — without rebuilding topology from scratch. NOT_FOUND if model_id doesn't exist.
	UpdateAndCalculatePowerFlow(context.Context, *UpdateAndCalculatePowerFlowRequest) (*CalculatePowerFlowResponse, error)
	// As UpdateAndCalculatePowerFlow, but runs a state estimation calculation. NOT_FOUND if model_id doesn't
	// exist.
	UpdateAndCalculateStateEstimation(context.Context, *UpdateAndCalculateStateEstimationRequest) (*CalculateStateEstimationResponse, error)
	// As UpdateAndCalculatePowerFlow, but runs an IEC 60909 short circuit calculation. NOT_FOUND if model_id
	// doesn't exist.
	UpdateAndCalculateShortCircuit(context.Context, *UpdateAndCalculateShortCircuitRequest) (*CalculateShortCircuitResponse, error)
	mustEmbedUnimplementedPowerGridServiceServer()
}

// UnimplementedPowerGridServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPowerGridServiceServer struct{}

func (UnimplementedPowerGridServiceServer) CalculatePowerFlow(context.Context, *CalculatePowerFlowRequest) (*CalculatePowerFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePowerFlow not implemented")
}
func (UnimplementedPowerGridServiceServer) CalculateStateEstimation(context.Context, *CalculateStateEstimationRequest) (*CalculateStateEstimationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateStateEstimation not implemented")
}
func (UnimplementedPowerGridServiceServer) CalculateShortCircuit(context.Context, *CalculateShortCircuitRequest) (*CalculateShortCircuitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateShortCircuit not implemented")
}
func (UnimplementedPowerGridServiceServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedPowerGridServiceServer) DestroyModel(context.Context, *DestroyModelRequest) (*DestroyModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyModel not implemented")
}
func (UnimplementedPowerGridServiceServer) UpdateAndCalculatePowerFlow(context.Context, *UpdateAndCalculatePowerFlowRequest) (*CalculatePowerFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAndCalculatePowerFlow not implemented")
}
func (UnimplementedPowerGridServiceServer) UpdateAndCalculateStateEstimation(context.Context, *UpdateAndCalculateStateEstimationRequest) (*CalculateStateEstimationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAndCalculateStateEstimation not implemented")
}
func (UnimplementedPowerGridServiceServer) UpdateAndCalculateShortCircuit(context.Context, *UpdateAndCalculateShortCircuitRequest) (*CalculateShortCircuitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAndCalculateShortCircuit not implemented")
}
func (UnimplementedPowerGridServiceServer) mustEmbedUnimplementedPowerGridServiceServer() {}
func (UnimplementedPowerGridServiceServer) testEmbeddedByValue()                          {}

// UnsafePowerGridServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PowerGridServiceServer will
// result in compilation errors.
type UnsafePowerGridServiceServer interface {
	mustEmbedUnimplementedPowerGridServiceServer()
}

func RegisterPowerGridServiceServer(s grpc.ServiceRegistrar, srv PowerGridServiceServer) {
	// If the following call pancis, it indicates UnimplementedPowerGridServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PowerGridService_ServiceDesc, srv)
}

func _PowerGridService_CalculatePowerFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePowerFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).CalculatePowerFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_CalculatePowerFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).CalculatePowerFlow(ctx, req.(*CalculatePowerFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_CalculateStateEstimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateStateEstimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).CalculateStateEstimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_CalculateStateEstimation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).CalculateStateEstimation(ctx, req.(*CalculateStateEstimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_CalculateShortCircuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateShortCircuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).CalculateShortCircuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_CalculateShortCircuit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).CalculateShortCircuit(ctx, req.(*CalculateShortCircuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_DestroyModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).DestroyModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_DestroyModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).DestroyModel(ctx, req.(*DestroyModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_UpdateAndCalculatePowerFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCalculatePowerFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).UpdateAndCalculatePowerFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_UpdateAndCalculatePowerFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).UpdateAndCalculatePowerFlow(ctx, req.(*UpdateAndCalculatePowerFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_UpdateAndCalculateStateEstimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCalculateStateEstimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).UpdateAndCalculateStateEstimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_UpdateAndCalculateStateEstimation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).UpdateAndCalculateStateEstimation(ctx, req.(*UpdateAndCalculateStateEstimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGridService_UpdateAndCalculateShortCircuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCalculateShortCircuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServiceServer).UpdateAndCalculateShortCircuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGridService_UpdateAndCalculateShortCircuit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServiceServer).UpdateAndCalculateShortCircuit(ctx, req.(*UpdateAndCalculateShortCircuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PowerGridService_ServiceDesc is the grpc.ServiceDesc for PowerGridService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PowerGridService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "power_grid_model.v1.PowerGridService",
	HandlerType: (*PowerGridServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePowerFlow",
			Handler:    _PowerGridService_CalculatePowerFlow_Handler,
		},
		{
			MethodName: "CalculateStateEstimation",
			Handler:    _PowerGridService_CalculateStateEstimation_Handler,
		},
		{
			MethodName: "CalculateShortCircuit",
			Handler:    _PowerGridService_CalculateShortCircuit_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _PowerGridService_CreateModel_Handler,
		},
		{
			MethodName: "DestroyModel",
			Handler:    _PowerGridService_DestroyModel_Handler,
		},
		{
			MethodName: "UpdateAndCalculatePowerFlow",
			Handler:    _PowerGridService_UpdateAndCalculatePowerFlow_Handler,
		},
		{
			MethodName: "UpdateAndCalculateStateEstimation",
			Handler:    _PowerGridService_UpdateAndCalculateStateEstimation_Handler,
		},
		{
			MethodName: "UpdateAndCalculateShortCircuit",
			Handler:    _PowerGridService_UpdateAndCalculateShortCircuit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "power_grid.proto",
}
