// SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: power_grid.proto

// Service definition for power_grid_grpc_server: a gRPC front end for power-grid-model's power flow, state
// estimation, and short circuit calculations. Request/response payloads carry PGM's own input/output dataset
// JSON (the same schema used by power_grid_model_c_example/serialization.c) as string fields, rather than
// mirroring every component/attribute as protobuf messages — see grpc_server/README.md for the full field
// reference and for the internal/pgmtypes Go package that builds that JSON from typed structs.

package powergridpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The numerical method used to solve a calculation. Shared across power flow and state estimation; only a
// subset of values is valid for each — see PowerFlowOptions.calculation_method and
// StateEstimationOptions.calculation_method.
type CalculationMethod int32

const (
	// No method chosen: the server picks a default appropriate to the calculation type (Newton-Raphson for
	// power flow, iterative linear for state estimation).
	CalculationMethod_CALCULATION_METHOD_UNSPECIFIED CalculationMethod = 0
	// Newton-Raphson iterative method. Valid for power flow or state estimation.
	CalculationMethod_CALCULATION_METHOD_NEWTON_RAPHSON CalculationMethod = 1
	// Linear (constant impedance) method. Power flow only.
	CalculationMethod_CALCULATION_METHOD_LINEAR CalculationMethod = 2
	// Iterative current method. Power flow only.
	CalculationMethod_CALCULATION_METHOD_ITERATIVE_CURRENT CalculationMethod = 3
	// Iterative linear method. State estimation only.
	CalculationMethod_CALCULATION_METHOD_ITERATIVE_LINEAR CalculationMethod = 4
)

// Enum value maps for CalculationMethod.
var (
	CalculationMethod_name = map[int32]string{
		0: "CALCULATION_METHOD_UNSPECIFIED",
		1: "CALCULATION_METHOD_NEWTON_RAPHSON",
		2: "CALCULATION_METHOD_LINEAR",
		3: "CALCULATION_METHOD_ITERATIVE_CURRENT",
		4: "CALCULATION_METHOD_ITERATIVE_LINEAR",
	}
	CalculationMethod_value = map[string]int32{
		"CALCULATION_METHOD_UNSPECIFIED":       0,
		"CALCULATION_METHOD_NEWTON_RAPHSON":    1,
		"CALCULATION_METHOD_LINEAR":            2,
		"CALCULATION_METHOD_ITERATIVE_CURRENT": 3,
		"CALCULATION_METHOD_ITERATIVE_LINEAR":  4,
	}
)

func (x CalculationMethod) Enum() *CalculationMethod {
	p := new(CalculationMethod)
	*p = x
	return p
}

func (x CalculationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_power_grid_proto_enumTypes[0].Descriptor()
}

func (CalculationMethod) Type() protoreflect.EnumType {
	return &file_power_grid_proto_enumTypes[0]
}

func (x CalculationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculationMethod.Descriptor instead.
func (CalculationMethod) EnumDescriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{0}
}

// Which IEC 60909 voltage factor (c) to use for a short circuit calculation: c_min gives the minimum short
// circuit current, c_max the maximum.
type ShortCircuitVoltageScaling int32

const (
	// No scaling chosen: the server defaults to maximum (c_max).
	ShortCircuitVoltageScaling_SHORT_CIRCUIT_VOLTAGE_SCALING_UNSPECIFIED ShortCircuitVoltageScaling = 0
	// c_min: minimum short circuit current.
	ShortCircuitVoltageScaling_SHORT_CIRCUIT_VOLTAGE_SCALING_MINIMUM ShortCircuitVoltageScaling = 1
	// c_max: maximum short circuit current.
	ShortCircuitVoltageScaling_SHORT_CIRCUIT_VOLTAGE_SCALING_MAXIMUM ShortCircuitVoltageScaling = 2
)

// Enum value maps for ShortCircuitVoltageScaling.
var (
	ShortCircuitVoltageScaling_name = map[int32]string{
		0: "SHORT_CIRCUIT_VOLTAGE_SCALING_UNSPECIFIED",
		1: "SHORT_CIRCUIT_VOLTAGE_SCALING_MINIMUM",
		2: "SHORT_CIRCUIT_VOLTAGE_SCALING_MAXIMUM",
	}
	ShortCircuitVoltageScaling_value = map[string]int32{
		"SHORT_CIRCUIT_VOLTAGE_SCALING_UNSPECIFIED": 0,
		"SHORT_CIRCUIT_VOLTAGE_SCALING_MINIMUM":     1,
		"SHORT_CIRCUIT_VOLTAGE_SCALING_MAXIMUM":     2,
	}
)

func (x ShortCircuitVoltageScaling) Enum() *ShortCircuitVoltageScaling {
	p := new(ShortCircuitVoltageScaling)
	*p = x
	return p
}

func (x ShortCircuitVoltageScaling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShortCircuitVoltageScaling) Descriptor() protoreflect.EnumDescriptor {
	return file_power_grid_proto_enumTypes[1].Descriptor()
}

func (ShortCircuitVoltageScaling) Type() protoreflect.EnumType {
	return &file_power_grid_proto_enumTypes[1]
}

func (x ShortCircuitVoltageScaling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShortCircuitVoltageScaling.Descriptor instead.
func (ShortCircuitVoltageScaling) EnumDescriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{1}
}

// Options for a power flow calculation (CalculatePowerFlow, UpdateAndCalculatePowerFlow).
type PowerFlowOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to run a symmetric (true) or asymmetric (false) calculation.
	//
	// Unset (false) together with proto3's inability to distinguish "unset" from "false" means the server always
	// treats this as an explicit choice — the Go client must always set it. See src/power_grid_service.cpp.
	Symmetric bool `protobuf:"varint,1,opt,name=symmetric,proto3" json:"symmetric,omitempty"`
	// Numerical method to use. CALCULATION_METHOD_UNSPECIFIED defaults to Newton-Raphson; only
	// CALCULATION_METHOD_NEWTON_RAPHSON, CALCULATION_METHOD_LINEAR, and CALCULATION_METHOD_ITERATIVE_CURRENT are
	// valid here.
	CalculationMethod CalculationMethod `protobuf:"varint,2,opt,name=calculation_method,json=calculationMethod,proto3,enum=power_grid_model.v1.CalculationMethod" json:"calculation_method,omitempty"`
	// Convergence tolerance for iterative methods. <= 0 means "use PGM's built-in default".
	ErrTol float64 `protobuf:"fixed64,3,opt,name=err_tol,json=errTol,proto3" json:"err_tol,omitempty"`
	// Maximum number of iterations for iterative methods. <= 0 means "use PGM's built-in default".
	MaxIter       int32 `protobuf:"varint,4,opt,name=max_iter,json=maxIter,proto3" json:"max_iter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerFlowOptions) Reset() {
	*x = PowerFlowOptions{}
	mi := &file_power_grid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerFlowOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerFlowOptions) ProtoMessage() {}

func (x *PowerFlowOptions) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerFlowOptions.ProtoReflect.Descriptor instead.
func (*PowerFlowOptions) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{0}
}

func (x *PowerFlowOptions) GetSymmetric() bool {
	if x != nil {
		return x.Symmetric
	}
	return false
}

func (x *PowerFlowOptions) GetCalculationMethod() CalculationMethod {
	if x != nil {
		return x.CalculationMethod
	}
	return CalculationMethod_CALCULATION_METHOD_UNSPECIFIED
}

func (x *PowerFlowOptions) GetErrTol() float64 {
	if x != nil {
		return x.ErrTol
	}
	return 0
}

func (x *PowerFlowOptions) GetMaxIter() int32 {
	if x != nil {
		return x.MaxIter
	}
	return 0
}

// Request for CalculatePowerFlow: a complete, self-contained grid to solve once.
type CalculatePowerFlowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System frequency in Hz, e.g. 50.0.
	SystemFrequency float64 `protobuf:"fixed64,1,opt,name=system_frequency,json=systemFrequency,proto3" json:"system_frequency,omitempty"`
	// PGM input dataset, PGM's own JSON schema (type "input").
	InputDatasetJson string `protobuf:"bytes,2,opt,name=input_dataset_json,json=inputDatasetJson,proto3" json:"input_dataset_json,omitempty"`
	// Calculation options.
	Options       *PowerFlowOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePowerFlowRequest) Reset() {
	*x = CalculatePowerFlowRequest{}
	mi := &file_power_grid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePowerFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePowerFlowRequest) ProtoMessage() {}

func (x *CalculatePowerFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePowerFlowRequest.ProtoReflect.Descriptor instead.
func (*CalculatePowerFlowRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePowerFlowRequest) GetSystemFrequency() float64 {
	if x != nil {
		return x.SystemFrequency
	}
	return 0
}

func (x *CalculatePowerFlowRequest) GetInputDatasetJson() string {
	if x != nil {
		return x.InputDatasetJson
	}
	return ""
}

func (x *CalculatePowerFlowRequest) GetOptions() *PowerFlowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Response for CalculatePowerFlow and UpdateAndCalculatePowerFlow.
type CalculatePowerFlowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PGM sym_output/asym_output dataset JSON (depending on PowerFlowOptions.symmetric).
	OutputDatasetJson string `protobuf:"bytes,1,opt,name=output_dataset_json,json=outputDatasetJson,proto3" json:"output_dataset_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculatePowerFlowResponse) Reset() {
	*x = CalculatePowerFlowResponse{}
	mi := &file_power_grid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePowerFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePowerFlowResponse) ProtoMessage() {}

func (x *CalculatePowerFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePowerFlowResponse.ProtoReflect.Descriptor instead.
func (*CalculatePowerFlowResponse) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{2}
}

func (x *CalculatePowerFlowResponse) GetOutputDatasetJson() string {
	if x != nil {
		return x.OutputDatasetJson
	}
	return ""
}

// Options for a state estimation calculation (CalculateStateEstimation, UpdateAndCalculateStateEstimation).
type StateEstimationOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to run a symmetric (true) or asymmetric (false) calculation.
	//
	// See PowerFlowOptions.symmetric: the Go client must always set this explicitly.
	Symmetric bool `protobuf:"varint,1,opt,name=symmetric,proto3" json:"symmetric,omitempty"`
	// Numerical method to use. CALCULATION_METHOD_UNSPECIFIED defaults to iterative linear; only
	// CALCULATION_METHOD_NEWTON_RAPHSON and CALCULATION_METHOD_ITERATIVE_LINEAR are valid here.
	CalculationMethod CalculationMethod `protobuf:"varint,2,opt,name=calculation_method,json=calculationMethod,proto3,enum=power_grid_model.v1.CalculationMethod" json:"calculation_method,omitempty"`
	// Convergence tolerance for iterative methods. <= 0 means "use PGM's built-in default".
	ErrTol float64 `protobuf:"fixed64,3,opt,name=err_tol,json=errTol,proto3" json:"err_tol,omitempty"`
	// Maximum number of iterations for iterative methods. <= 0 means "use PGM's built-in default".
	MaxIter       int32 `protobuf:"varint,4,opt,name=max_iter,json=maxIter,proto3" json:"max_iter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEstimationOptions) Reset() {
	*x = StateEstimationOptions{}
	mi := &file_power_grid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEstimationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEstimationOptions) ProtoMessage() {}

func (x *StateEstimationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEstimationOptions.ProtoReflect.Descriptor instead.
func (*StateEstimationOptions) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{3}
}

func (x *StateEstimationOptions) GetSymmetric() bool {
	if x != nil {
		return x.Symmetric
	}
	return false
}

func (x *StateEstimationOptions) GetCalculationMethod() CalculationMethod {
	if x != nil {
		return x.CalculationMethod
	}
	return CalculationMethod_CALCULATION_METHOD_UNSPECIFIED
}

func (x *StateEstimationOptions) GetErrTol() float64 {
	if x != nil {
		return x.ErrTol
	}
	return 0
}

func (x *StateEstimationOptions) GetMaxIter() int32 {
	if x != nil {
		return x.MaxIter
	}
	return 0
}

// Request for CalculateStateEstimation: a complete, self-contained grid (including sensor measurements) to
// solve once.
type CalculateStateEstimationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System frequency in Hz, e.g. 50.0.
	SystemFrequency float64 `protobuf:"fixed64,1,opt,name=system_frequency,json=systemFrequency,proto3" json:"system_frequency,omitempty"`
	// PGM input dataset, including sensor components (e.g. sym_voltage_sensor, sym_power_sensor), PGM's own
	// JSON schema (type "input").
	InputDatasetJson string `protobuf:"bytes,2,opt,name=input_dataset_json,json=inputDatasetJson,proto3" json:"input_dataset_json,omitempty"`
	// Calculation options.
	Options       *StateEstimationOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStateEstimationRequest) Reset() {
	*x = CalculateStateEstimationRequest{}
	mi := &file_power_grid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStateEstimationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStateEstimationRequest) ProtoMessage() {}

func (x *CalculateStateEstimationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStateEstimationRequest.ProtoReflect.Descriptor instead.
func (*CalculateStateEstimationRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateStateEstimationRequest) GetSystemFrequency() float64 {
	if x != nil {
		return x.SystemFrequency
	}
	return 0
}

func (x *CalculateStateEstimationRequest) GetInputDatasetJson() string {
	if x != nil {
		return x.InputDatasetJson
	}
	return ""
}

func (x *CalculateStateEstimationRequest) GetOptions() *StateEstimationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Response for CalculateStateEstimation and UpdateAndCalculateStateEstimation.
type CalculateStateEstimationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PGM sym_output/asym_output dataset JSON (depending on StateEstimationOptions.symmetric).
	OutputDatasetJson string `protobuf:"bytes,1,opt,name=output_dataset_json,json=outputDatasetJson,proto3" json:"output_dataset_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculateStateEstimationResponse) Reset() {
	*x = CalculateStateEstimationResponse{}
	mi := &file_power_grid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStateEstimationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStateEstimationResponse) ProtoMessage() {}

func (x *CalculateStateEstimationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStateEstimationResponse.ProtoReflect.Descriptor instead.
func (*CalculateStateEstimationResponse) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateStateEstimationResponse) GetOutputDatasetJson() string {
	if x != nil {
		return x.OutputDatasetJson
	}
	return ""
}

// Options for a short circuit calculation (CalculateShortCircuit, UpdateAndCalculateShortCircuit). There is no
// calculation_method option here: IEC 60909 (CALCULATION_METHOD_UNSPECIFIED's implied default) is the only
// method PGM supports for short circuit.
type ShortCircuitOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which IEC 60909 voltage factor to use. SHORT_CIRCUIT_VOLTAGE_SCALING_UNSPECIFIED defaults to maximum.
	VoltageScaling ShortCircuitVoltageScaling `protobuf:"varint,1,opt,name=voltage_scaling,json=voltageScaling,proto3,enum=power_grid_model.v1.ShortCircuitVoltageScaling" json:"voltage_scaling,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShortCircuitOptions) Reset() {
	*x = ShortCircuitOptions{}
	mi := &file_power_grid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortCircuitOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortCircuitOptions) ProtoMessage() {}

func (x *ShortCircuitOptions) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortCircuitOptions.ProtoReflect.Descriptor instead.
func (*ShortCircuitOptions) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{6}
}

func (x *ShortCircuitOptions) GetVoltageScaling() ShortCircuitVoltageScaling {
	if x != nil {
		return x.VoltageScaling
	}
	return ShortCircuitVoltageScaling_SHORT_CIRCUIT_VOLTAGE_SCALING_UNSPECIFIED
}

// Request for CalculateShortCircuit: a complete, self-contained grid (including at least one fault) to solve
// once.
type CalculateShortCircuitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System frequency in Hz, e.g. 50.0.
	SystemFrequency float64 `protobuf:"fixed64,1,opt,name=system_frequency,json=systemFrequency,proto3" json:"system_frequency,omitempty"`
	// PGM input dataset, including a fault component, PGM's own JSON schema (type "input").
	InputDatasetJson string `protobuf:"bytes,2,opt,name=input_dataset_json,json=inputDatasetJson,proto3" json:"input_dataset_json,omitempty"`
	// Calculation options.
	Options       *ShortCircuitOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateShortCircuitRequest) Reset() {
	*x = CalculateShortCircuitRequest{}
	mi := &file_power_grid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateShortCircuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateShortCircuitRequest) ProtoMessage() {}

func (x *CalculateShortCircuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateShortCircuitRequest.ProtoReflect.Descriptor instead.
func (*CalculateShortCircuitRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateShortCircuitRequest) GetSystemFrequency() float64 {
	if x != nil {
		return x.SystemFrequency
	}
	return 0
}

func (x *CalculateShortCircuitRequest) GetInputDatasetJson() string {
	if x != nil {
		return x.InputDatasetJson
	}
	return ""
}

func (x *CalculateShortCircuitRequest) GetOptions() *ShortCircuitOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Response for CalculateShortCircuit and UpdateAndCalculateShortCircuit.
type CalculateShortCircuitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PGM sc_output dataset JSON. Always per-phase (a/b/c), even for a symmetrical (three-phase) fault.
	OutputDatasetJson string `protobuf:"bytes,1,opt,name=output_dataset_json,json=outputDatasetJson,proto3" json:"output_dataset_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculateShortCircuitResponse) Reset() {
	*x = CalculateShortCircuitResponse{}
	mi := &file_power_grid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateShortCircuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateShortCircuitResponse) ProtoMessage() {}

func (x *CalculateShortCircuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateShortCircuitResponse.ProtoReflect.Descriptor instead.
func (*CalculateShortCircuitResponse) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateShortCircuitResponse) GetOutputDatasetJson() string {
	if x != nil {
		return x.OutputDatasetJson
	}
	return ""
}

// Request for CreateModel: a complete, self-contained grid to build a long-lived model from.
type CreateModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System frequency in Hz, e.g. 50.0.
	SystemFrequency float64 `protobuf:"fixed64,1,opt,name=system_frequency,json=systemFrequency,proto3" json:"system_frequency,omitempty"`
	// PGM input dataset, PGM's own JSON schema (type "input").
	InputDatasetJson string `protobuf:"bytes,2,opt,name=input_dataset_json,json=inputDatasetJson,proto3" json:"input_dataset_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_power_grid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{9}
}

func (x *CreateModelRequest) GetSystemFrequency() float64 {
	if x != nil {
		return x.SystemFrequency
	}
	return 0
}

func (x *CreateModelRequest) GetInputDatasetJson() string {
	if x != nil {
		return x.InputDatasetJson
	}
	return ""
}

// Response for CreateModel.
type CreateModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated key for the created model; pass this to UpdateAndCalculate*/DestroyModel. See the
	// "Stateful model session API" note above for its caveats (not authenticated, no expiry).
	ModelId       string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_power_grid_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{10}
}

func (x *CreateModelResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Request for DestroyModel.
type DestroyModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model_id previously returned by CreateModel.
	ModelId       string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyModelRequest) Reset() {
	*x = DestroyModelRequest{}
	mi := &file_power_grid_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyModelRequest) ProtoMessage() {}

func (x *DestroyModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyModelRequest.ProtoReflect.Descriptor instead.
func (*DestroyModelRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Response for DestroyModel. Always empty; success is indicated by the RPC status (NOT_FOUND if model_id
// doesn't exist).
type DestroyModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyModelResponse) Reset() {
	*x = DestroyModelResponse{}
	mi := &file_power_grid_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyModelResponse) ProtoMessage() {}

func (x *DestroyModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyModelResponse.ProtoReflect.Descriptor instead.
func (*DestroyModelResponse) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{12}
}

// Request for UpdateAndCalculatePowerFlow.
type UpdateAndCalculatePowerFlowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model_id previously returned by CreateModel.
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// PGM update dataset JSON (type "update"): only the component IDs/attributes that changed since the model
	// was created or last updated. May be empty to recalculate without changing anything.
	UpdateDatasetJson string `protobuf:"bytes,2,opt,name=update_dataset_json,json=updateDatasetJson,proto3" json:"update_dataset_json,omitempty"`
	// Calculation options.
	Options       *PowerFlowOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAndCalculatePowerFlowRequest) Reset() {
	*x = UpdateAndCalculatePowerFlowRequest{}
	mi := &file_power_grid_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAndCalculatePowerFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAndCalculatePowerFlowRequest) ProtoMessage() {}

func (x *UpdateAndCalculatePowerFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAndCalculatePowerFlowRequest.ProtoReflect.Descriptor instead.
func (*UpdateAndCalculatePowerFlowRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAndCalculatePowerFlowRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *UpdateAndCalculatePowerFlowRequest) GetUpdateDatasetJson() string {
	if x != nil {
		return x.UpdateDatasetJson
	}
	return ""
}

func (x *UpdateAndCalculatePowerFlowRequest) GetOptions() *PowerFlowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Request for UpdateAndCalculateStateEstimation.
type UpdateAndCalculateStateEstimationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model_id previously returned by CreateModel.
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// PGM update dataset JSON (type "update"): only the component IDs/attributes that changed since the model
	// was created or last updated (e.g. a new sensor measurement). May be empty to recalculate without
	// changing anything.
	UpdateDatasetJson string `protobuf:"bytes,2,opt,name=update_dataset_json,json=updateDatasetJson,proto3" json:"update_dataset_json,omitempty"`
	// Calculation options.
	Options       *StateEstimationOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAndCalculateStateEstimationRequest) Reset() {
	*x = UpdateAndCalculateStateEstimationRequest{}
	mi := &file_power_grid_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAndCalculateStateEstimationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAndCalculateStateEstimationRequest) ProtoMessage() {}

func (x *UpdateAndCalculateStateEstimationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAndCalculateStateEstimationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAndCalculateStateEstimationRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAndCalculateStateEstimationRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *UpdateAndCalculateStateEstimationRequest) GetUpdateDatasetJson() string {
	if x != nil {
		return x.UpdateDatasetJson
	}
	return ""
}

func (x *UpdateAndCalculateStateEstimationRequest) GetOptions() *StateEstimationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Request for UpdateAndCalculateShortCircuit.
type UpdateAndCalculateShortCircuitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model_id previously returned by CreateModel.
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// PGM update dataset JSON (type "update"): only the component IDs/attributes that changed since the model
	// was created or last updated (e.g. a fault being toggled active). May be empty to recalculate without
	// changing anything.
	UpdateDatasetJson string `protobuf:"bytes,2,opt,name=update_dataset_json,json=updateDatasetJson,proto3" json:"update_dataset_json,omitempty"`
	// Calculation options.
	Options       *ShortCircuitOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAndCalculateShortCircuitRequest) Reset() {
	*x = UpdateAndCalculateShortCircuitRequest{}
	mi := &file_power_grid_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAndCalculateShortCircuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAndCalculateShortCircuitRequest) ProtoMessage() {}

func (x *UpdateAndCalculateShortCircuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_grid_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAndCalculateShortCircuitRequest.ProtoReflect.Descriptor instead.
func (*UpdateAndCalculateShortCircuitRequest) Descriptor() ([]byte, []int) {
	return file_power_grid_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAndCalculateShortCircuitRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *UpdateAndCalculateShortCircuitRequest) GetUpdateDatasetJson() string {
	if x != nil {
		return x.UpdateDatasetJson
	}
	return ""
}

func (x *UpdateAndCalculateShortCircuitRequest) GetOptions() *ShortCircuitOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_power_grid_proto protoreflect.FileDescriptor

const file_power_grid_proto_rawDesc = "" +
	"\n" +
	"\x10power_grid.proto\x12\x13power_grid_model.v1\"\xbb\x01\n" +
	"\x10PowerFlowOptions\x12\x1c\n" +
	"\tsymmetric\x18\x01 \x01(\bR\tsymmetric\x12U\n" +
	"\x12calculation_method\x18\x02 \x01(\x0e2&.power_grid_model.v1.CalculationMethodR\x11calculationMethod\x12\x17\n" +
	"\aerr_tol\x18\x03 \x01(\x01R\x06errTol\x12\x19\n" +
	"\bmax_iter\x18\x04 \x01(\x05R\amaxIter\"\xb5\x01\n" +
	"\x19CalculatePowerFlowRequest\x12)\n" +
	"\x10system_frequency\x18\x01 \x01(\x01R\x0fsystemFrequency\x12,\n" +
	"\x12input_dataset_json\x18\x02 \x01(\tR\x10inputDatasetJson\x12?\n" +
	"\aoptions\x18\x03 \x01(\v2%.power_grid_model.v1.PowerFlowOptionsR\aoptions\"L\n" +
	"\x1aCalculatePowerFlowResponse\x12.\n" +
	"\x13output_dataset_json\x18\x01 \x01(\tR\x11outputDatasetJson\"\xc1\x01\n" +
	"\x16StateEstimationOptions\x12\x1c\n" +
	"\tsymmetric\x18\x01 \x01(\bR\tsymmetric\x12U\n" +
	"\x12calculation_method\x18\x02 \x01(\x0e2&.power_grid_model.v1.CalculationMethodR\x11calculationMethod\x12\x17\n" +
	"\aerr_tol\x18\x03 \x01(\x01R\x06errTol\x12\x19\n" +
	"\bmax_iter\x18\x04 \x01(\x05R\amaxIter\"\xc1\x01\n" +
	"\x1fCalculateStateEstimationRequest\x12)\n" +
	"\x10system_frequency\x18\x01 \x01(\x01R\x0fsystemFrequency\x12,\n" +
	"\x12input_dataset_json\x18\x02 \x01(\tR\x10inputDatasetJson\x12E\n" +
	"\aoptions\x18\x03 \x01(\v2+.power_grid_model.v1.StateEstimationOptionsR\aoptions\"R\n" +
	" CalculateStateEstimationResponse\x12.\n" +
	"\x13output_dataset_json\x18\x01 \x01(\tR\x11outputDatasetJson\"o\n" +
	"\x13ShortCircuitOptions\x12X\n" +
	"\x0fvoltage_scaling\x18\x01 \x01(\x0e2/.power_grid_model.v1.ShortCircuitVoltageScalingR\x0evoltageScaling\"\xbb\x01\n" +
	"\x1cCalculateShortCircuitRequest\x12)\n" +
	"\x10system_frequency\x18\x01 \x01(\x01R\x0fsystemFrequency\x12,\n" +
	"\x12input_dataset_json\x18\x02 \x01(\tR\x10inputDatasetJson\x12B\n" +
	"\aoptions\x18\x03 \x01(\v2(.power_grid_model.v1.ShortCircuitOptionsR\aoptions\"O\n" +
	"\x1dCalculateShortCircuitResponse\x12.\n" +
	"\x13output_dataset_json\x18\x01 \x01(\tR\x11outputDatasetJson\"m\n" +
	"\x12CreateModelRequest\x12)\n" +
	"\x10system_frequency\x18\x01 \x01(\x01R\x0fsystemFrequency\x12,\n" +
	"\x12input_dataset_json\x18\x02 \x01(\tR\x10inputDatasetJson\"0\n" +
	"\x13CreateModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"0\n" +
	"\x13DestroyModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\x16\n" +
	"\x14DestroyModelResponse\"\xb0\x01\n" +
	"\"UpdateAndCalculatePowerFlowRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12.\n" +
	"\x13update_dataset_json\x18\x02 \x01(\tR\x11updateDatasetJson\x12?\n" +
	"\aoptions\x18\x03 \x01(\v2%.power_grid_model.v1.PowerFlowOptionsR\aoptions\"\xbc\x01\n" +
	"(UpdateAndCalculateStateEstimationRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12.\n" +
	"\x13update_dataset_json\x18\x02 \x01(\tR\x11updateDatasetJson\x12E\n" +
	"\aoptions\x18\x03 \x01(\v2+.power_grid_model.v1.StateEstimationOptionsR\aoptions\"\xb6\x01\n" +
	"%UpdateAndCalculateShortCircuitRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12.\n" +
	"\x13update_dataset_json\x18\x02 \x01(\tR\x11updateDatasetJson\x12B\n" +
	"\aoptions\x18\x03 \x01(\v2(.power_grid_model.v1.ShortCircuitOptionsR\aoptions*\xd0\x01\n" +
	"\x11CalculationMethod\x12\"\n" +
	"\x1eCALCULATION_METHOD_UNSPECIFIED\x10\x00\x12%\n" +
	"!CALCULATION_METHOD_NEWTON_RAPHSON\x10\x01\x12\x1d\n" +
	"\x19CALCULATION_METHOD_LINEAR\x10\x02\x12(\n" +
	"$CALCULATION_METHOD_ITERATIVE_CURRENT\x10\x03\x12'\n" +
	"#CALCULATION_METHOD_ITERATIVE_LINEAR\x10\x04*\xa1\x01\n" +
	"\x1aShortCircuitVoltageScaling\x12-\n" +
	")SHORT_CIRCUIT_VOLTAGE_SCALING_UNSPECIFIED\x10\x00\x12)\n" +
	"%SHORT_CIRCUIT_VOLTAGE_SCALING_MINIMUM\x10\x01\x12)\n" +
	"%SHORT_CIRCUIT_VOLTAGE_SCALING_MAXIMUM\x10\x022\x93\b\n" +
	"\x10PowerGridService\x12u\n" +
	"\x12CalculatePowerFlow\x12..power_grid_model.v1.CalculatePowerFlowRequest\x1a/.power_grid_model.v1.CalculatePowerFlowResponse\x12\x87\x01\n" +
	"\x18CalculateStateEstimation\x124.power_grid_model.v1.CalculateStateEstimationRequest\x1a5.power_grid_model.v1.CalculateStateEstimationResponse\x12~\n" +
	"\x15CalculateShortCircuit\x121.power_grid_model.v1.CalculateShortCircuitRequest\x1a2.power_grid_model.v1.CalculateShortCircuitResponse\x12`\n" +
	"\vCreateModel\x12'.power_grid_model.v1.CreateModelRequest\x1a(.power_grid_model.v1.CreateModelResponse\x12c\n" +
	"\fDestroyModel\x12(.power_grid_model.v1.DestroyModelRequest\x1a).power_grid_model.v1.DestroyModelResponse\x12\x87\x01\n" +
	"\x1bUpdateAndCalculatePowerFlow\x127.power_grid_model.v1.UpdateAndCalculatePowerFlowRequest\x1a/.power_grid_model.v1.CalculatePowerFlowResponse\x12\x99\x01\n" +
	"!UpdateAndCalculateStateEstimation\x12=.power_grid_model.v1.UpdateAndCalculateStateEstimationRequest\x1a5.power_grid_model.v1.CalculateStateEstimationResponse\x12\x90\x01\n" +
	"\x1eUpdateAndCalculateShortCircuit\x12:.power_grid_model.v1.UpdateAndCalculateShortCircuitRequest\x1a2.power_grid_model.v1.CalculateShortCircuitResponseBGZEpower-grid-model/grpc_client_example/internal/powergridpb;powergridpbb\x06proto3"

var (
	file_power_grid_proto_rawDescOnce sync.Once
	file_power_grid_proto_rawDescData []byte
)

func file_power_grid_proto_rawDescGZIP() []byte {
	file_power_grid_proto_rawDescOnce.Do(func() {
		file_power_grid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_power_grid_proto_rawDesc), len(file_power_grid_proto_rawDesc)))
	})
	return file_power_grid_proto_rawDescData
}

var file_power_grid_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_power_grid_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_power_grid_proto_goTypes = []any{
	(CalculationMethod)(0),                           // 0: power_grid_model.v1.CalculationMethod
	(ShortCircuitVoltageScaling)(0),                  // 1: power_grid_model.v1.ShortCircuitVoltageScaling
	(*PowerFlowOptions)(nil),                         // 2: power_grid_model.v1.PowerFlowOptions
	(*CalculatePowerFlowRequest)(nil),                // 3: power_grid_model.v1.CalculatePowerFlowRequest
	(*CalculatePowerFlowResponse)(nil),               // 4: power_grid_model.v1.CalculatePowerFlowResponse
	(*StateEstimationOptions)(nil),                   // 5: power_grid_model.v1.StateEstimationOptions
	(*CalculateStateEstimationRequest)(nil),          // 6: power_grid_model.v1.CalculateStateEstimationRequest
	(*CalculateStateEstimationResponse)(nil),         // 7: power_grid_model.v1.CalculateStateEstimationResponse
	(*ShortCircuitOptions)(nil),                      // 8: power_grid_model.v1.ShortCircuitOptions
	(*CalculateShortCircuitRequest)(nil),             // 9: power_grid_model.v1.CalculateShortCircuitRequest
	(*CalculateShortCircuitResponse)(nil),            // 10: power_grid_model.v1.CalculateShortCircuitResponse
	(*CreateModelRequest)(nil),                       // 11: power_grid_model.v1.CreateModelRequest
	(*CreateModelResponse)(nil),                      // 12: power_grid_model.v1.CreateModelResponse
	(*DestroyModelRequest)(nil),                      // 13: power_grid_model.v1.DestroyModelRequest
	(*DestroyModelResponse)(nil),                     // 14: power_grid_model.v1.DestroyModelResponse
	(*UpdateAndCalculatePowerFlowRequest)(nil),       // 15: power_grid_model.v1.UpdateAndCalculatePowerFlowRequest
	(*UpdateAndCalculateStateEstimationRequest)(nil), // 16: power_grid_model.v1.UpdateAndCalculateStateEstimationRequest
	(*UpdateAndCalculateShortCircuitRequest)(nil),    // 17: power_grid_model.v1.UpdateAndCalculateShortCircuitRequest
}
var file_power_grid_proto_depIdxs = []int32{
	0,  // 0: power_grid_model.v1.PowerFlowOptions.calculation_method:type_name -> power_grid_model.v1.CalculationMethod
	2,  // 1: power_grid_model.v1.CalculatePowerFlowRequest.options:type_name -> power_grid_model.v1.PowerFlowOptions
	0,  // 2: power_grid_model.v1.StateEstimationOptions.calculation_method:type_name -> power_grid_model.v1.CalculationMethod
	5,  // 3: power_grid_model.v1.CalculateStateEstimationRequest.options:type_name -> power_grid_model.v1.StateEstimationOptions
	1,  // 4: power_grid_model.v1.ShortCircuitOptions.voltage_scaling:type_name -> power_grid_model.v1.ShortCircuitVoltageScaling
	8,  // 5: power_grid_model.v1.CalculateShortCircuitRequest.options:type_name -> power_grid_model.v1.ShortCircuitOptions
	2,  // 6: power_grid_model.v1.UpdateAndCalculatePowerFlowRequest.options:type_name -> power_grid_model.v1.PowerFlowOptions
	5,  // 7: power_grid_model.v1.UpdateAndCalculateStateEstimationRequest.options:type_name -> power_grid_model.v1.StateEstimationOptions
	8,  // 8: power_grid_model.v1.UpdateAndCalculateShortCircuitRequest.options:type_name -> power_grid_model.v1.ShortCircuitOptions
	3,  // 9: power_grid_model.v1.PowerGridService.CalculatePowerFlow:input_type -> power_grid_model.v1.CalculatePowerFlowRequest
	6,  // 10: power_grid_model.v1.PowerGridService.CalculateStateEstimation:input_type -> power_grid_model.v1.CalculateStateEstimationRequest
	9,  // 11: power_grid_model.v1.PowerGridService.CalculateShortCircuit:input_type -> power_grid_model.v1.CalculateShortCircuitRequest
	11, // 12: power_grid_model.v1.PowerGridService.CreateModel:input_type -> power_grid_model.v1.CreateModelRequest
	13, // 13: power_grid_model.v1.PowerGridService.DestroyModel:input_type -> power_grid_model.v1.DestroyModelRequest
	15, // 14: power_grid_model.v1.PowerGridService.UpdateAndCalculatePowerFlow:input_type -> power_grid_model.v1.UpdateAndCalculatePowerFlowRequest
	16, // 15: power_grid_model.v1.PowerGridService.UpdateAndCalculateStateEstimation:input_type -> power_grid_model.v1.UpdateAndCalculateStateEstimationRequest
	17, // 16: power_grid_model.v1.PowerGridService.UpdateAndCalculateShortCircuit:input_type -> power_grid_model.v1.UpdateAndCalculateShortCircuitRequest
	4,  // 17: power_grid_model.v1.PowerGridService.CalculatePowerFlow:output_type -> power_grid_model.v1.CalculatePowerFlowResponse
	7,  // 18: power_grid_model.v1.PowerGridService.CalculateStateEstimation:output_type -> power_grid_model.v1.CalculateStateEstimationResponse
	10, // 19: power_grid_model.v1.PowerGridService.CalculateShortCircuit:output_type -> power_grid_model.v1.CalculateShortCircuitResponse
	12, // 20: power_grid_model.v1.PowerGridService.CreateModel:output_type -> power_grid_model.v1.CreateModelResponse
	14, // 21: power_grid_model.v1.PowerGridService.DestroyModel:output_type -> power_grid_model.v1.DestroyModelResponse
	4,  // 22: power_grid_model.v1.PowerGridService.UpdateAndCalculatePowerFlow:output_type -> power_grid_model.v1.CalculatePowerFlowResponse
	7,  // 23: power_grid_model.v1.PowerGridService.UpdateAndCalculateStateEstimation:output_type -> power_grid_model.v1.CalculateStateEstimationResponse
	10, // 24: power_grid_model.v1.PowerGridService.UpdateAndCalculateShortCircuit:output_type -> power_grid_model.v1.CalculateShortCircuitResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_power_grid_proto_init() }
func file_power_grid_proto_init() {
	if File_power_grid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_power_grid_proto_rawDesc), len(file_power_grid_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_power_grid_proto_goTypes,
		DependencyIndexes: file_power_grid_proto_depIdxs,
		EnumInfos:         file_power_grid_proto_enumTypes,
		MessageInfos:      file_power_grid_proto_msgTypes,
	}.Build()
	File_power_grid_proto = out.File
	file_power_grid_proto_goTypes = nil
	file_power_grid_proto_depIdxs = nil
}
